c
c
c
      subroutine defcor (coregn)
c
c ... this subroutine was auto-generated by
c     /home/gerard/pdb/phipsi/statjiffy.f
c
c ... COREGN will be set to 1 for all 10*10 degree squared
c     areas of the Ramachandran plot in which 98% of all
c     residues in ~400 <95% homologous <=2.0 A structures
c     are found
c
      implicit NONE
c
      integer m37
      parameter (m37=37*37)
c
      integer coregn (m37),i
c
code ...
c
      do i=1,m37
        coregn(i) = 0
      end do
c
      do i =    2,  11
        coregn (i) = 1
      end do
      do i =   40,  42
        coregn (i) = 1
      end do
      do i =   46,  47
        coregn (i) = 1
      end do
      coregn ( 414) = 1
      do i =  417, 422
        coregn (i) = 1
      end do
      do i =  451, 459
        coregn (i) = 1
      end do
      do i =  487, 496
        coregn (i) = 1
      end do
      do i =  524, 532
        coregn (i) = 1
      end do
      do i =  560, 569
        coregn (i) = 1
      end do
      do i =  597, 605
        coregn (i) = 1
      end do
      do i =  634, 641
        coregn (i) = 1
      end do
      do i =  670, 677
        coregn (i) = 1
      end do
      do i =  691, 692
        coregn (i) = 1
      end do
      do i =  708, 714
        coregn (i) = 1
      end do
      do i =  728, 729
        coregn (i) = 1
      end do
      do i =  745, 750
        coregn (i) = 1
      end do
      do i =  764, 766
        coregn (i) = 1
      end do
      do i =  782, 785
        coregn (i) = 1
      end do
      do i =  800, 802
        coregn (i) = 1
      end do
      do i =  819, 821
        coregn (i) = 1
      end do
      do i =  837, 839
        coregn (i) = 1
      end do
      do i =  856, 857
        coregn (i) = 1
      end do
      do i =  861, 862
        coregn (i) = 1
      end do
      do i =  874, 876
        coregn (i) = 1
      end do
      do i =  892, 894
        coregn (i) = 1
      end do
      do i =  897, 899
        coregn (i) = 1
      end do
      do i =  911, 912
        coregn (i) = 1
      end do
      do i =  929, 931
        coregn (i) = 1
      end do
      do i =  934, 936
        coregn (i) = 1
      end do
      do i =  966, 973
        coregn (i) = 1
      end do
      do i = 1002,1010
        coregn (i) = 1
      end do
      do i = 1039,1048
        coregn (i) = 1
      end do
      do i = 1076,1087
        coregn (i) = 1
      end do
      do i = 1112,1124
        coregn (i) = 1
      end do
      do i = 1149,1161
        coregn (i) = 1
      end do
      do i = 1186,1198
        coregn (i) = 1
      end do
      do i = 1222,1234
        coregn (i) = 1
      end do
      do i = 1258,1271
        coregn (i) = 1
      end do
      do i = 1295,1307
        coregn (i) = 1
      end do
      coregn (1332) = 1
      do i = 1334,1343
        coregn (i) = 1
      end do
c
      return
      end
