c
c
c
	SUBROUTINE getr5  (LUN,MIFD,NSIZE,RHO,RHORNG,NRHO,IBP0,IERROR)
C
      implicit none
c
	INTEGER*4 maxr5buf     ,NSIZE
	PARAMETER (maxr5buf=10000)
	REAL*4    RHO(NSIZE)  ,RHORNG(6)   ,BUF(maxr5buf)
      real tmin,tmax,tmid,trat,r,rsq
	INTEGER*2 IP	    ,NB	    ,I2BUF(2*maxr5buf)
	INTEGER*4 I4BUF(1000) ,BLID	  ,NWR	   ,NLAY	
	INTEGER*4 LINE	  ,LNTH	  ,MIFD(9)     ,NRHO
	INTEGER*4 LUN	   ,IERROR	,NLINES	,LENLIN
	INTEGER*4 LL2	   ,NWLINE	,IRHO	  ,ILINE
	INTEGER*4 IBP0	  ,IB	    ,IOS	   ,IBPDEN
	INTEGER*4 IL	    ,IBP  
	EQUIVALENCE (BUF(1),I4BUF(1),I2BUF(1))
C
	IERROR    = 0
	NLINES    = MIFD(2) - MIFD(1) + 1
	LENLIN    = MIFD(5) - MIFD(4) + 1
	LL2	 = (LENLIN+1)/2
	NWLINE    = LL2 + 3
	IRHO	= 0
	ILINE     = 0
C
C   Loop back to here if several blocks for the layer
C
  100 IF(IBP0.LE.0) THEN
	READ(LUN,ERR=900,IOSTAT=IOS)BLID,IP,NB,(BUF(IB),IB=1,NB)
	IF(BLID.NE.5) GO TO 910
	IF(NB.LT.4 .OR. NB.GT.maxr5buf) GO TO 920
	IBP0 = 0
	END IF
C
	IF(ILINE.LE.0) THEN
	NWR	 = I4BUF(IBP0+1)
	NLAY	= I4BUF(IBP0+2)
	LINE	= I4BUF(IBP0+3)
	LNTH	= I4BUF(IBP0+4)
	IBP0	= IBP0 + 4
	ILINE     = 1
	IF(NWR.NE.3) GOTO 930
	IF (LINE.NE.NLINES) GOTO 940
	IF (LNTH.NE.LENLIN)GO TO 950
	END IF
C
	IBP	 = IBP0
  110 IF(ILINE.LE.NLINES .AND. IBP+NWLINE.LE.NB) THEN
	NWR	 = I4BUF(IBP+1)
	TMIN	= BUF(IBP+2)
	TMAX	= BUF(IBP+3)
	IF(NWR.NE.NWLINE-1) GO TO 960
	TMID	= 0.5*(TMIN + TMAX)
	TRAT	= (TMAX-TMIN)/65536.
	IBPDEN    =  2*(IBP + 3)
C
	DO 120 IL  = 1,LNTH
	IRHO	= IRHO+1
	IBPDEN    = IBPDEN+1
	R	   = TMID + TRAT*I2BUF(IBPDEN)
	RHO(IRHO) = R
	RSQ	 = R * R
	RHORNG(1) = AMIN1(RHORNG(1),R)
	RHORNG(2) = AMAX1(RHORNG(2),R)
	RHORNG(3) = RHORNG(3) + R
	RHORNG(4) = RHORNG(4) + RSQ
	RHORNG(5) = RHORNG(5) + R*RSQ
	RHORNG(6) = RHORNG(6) + RSQ*RSQ
  120 CONTINUE
	IBP	 = IBP + (NWLINE)
	ILINE     = ILINE + 1
	GO TO 110 
	END IF
C
	IBP0	= IBP
	IF(IBP0.GE.NB) IBP0 = 0
	IF(ILINE.LE.NLINES) GO TO 100
	NRHO	= NRHO + IRHO
	RETURN
C
C   ERRORS
C
  900 IERROR = 1
	WRITE (6,1000) IOS
	RETURN
C
  910 IERROR = 2
	WRITE (6,1100) BLID
	RETURN
C
  920 IERROR = 7
	WRITE (6,1200) NB, maxr5buf
	RETURN
C
  930 IERROR = 8
	WRITE (6,1300) NWR
	RETURN
C
  940 IERROR = 9
	WRITE (6,1400) LINE, NLINES
	RETURN
C
  950 IERROR = 10
	WRITE (6,1500) LNTH,LENLIN
	RETURN
C
  960 IERROR   = 11
	WRITE (6,1600) NWR, NWLINE-1
	RETURN
C
 1000 FORMAT (' MAP> Error reading R5 record (IOSTAT=',I5,')')
 1100 FORMAT (' MAP> Record R5 block-id = ',I5,' (should be 5)')
 1200 FORMAT (' MAP> Value of NB in record R5 =',I8,' <4 or >',I5)
 1300 FORMAT (' MAP> Value of NWR in record R5 = ',I12,' (should be 3)')
 1400 FORMAT (' MAP> Value of LINE in record R5 =',I12,' not', I5)
 1500 FORMAT (' MAP> Value of LENGTH in record R5 =',I12,' not', I5)
 1600 FORMAT (' MAP> Value of NWR in record R5 = ',I12,' not',I5)
c
	END
